# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PucJQbtXgk8cGhCxLZtCoojeX5nQkftf
"""

!pip install prettytable

from prettytable import PrettyTable

receipt = PrettyTable()
receipt.field_names = ['№', 'Продукт', 'Цена', 'Количество', 'Стоимость']

print(receipt)